"""
Student information for this assignment:

Replace <FULL NAME> with your name.
On my/our honor, Erik Loyola, this
programming assignment is my own work and I have not provided this code to
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1: ek22296
"""


def rail_fence_encode(string, key):
    """
    pre: string is a string of characters and key is a positive
        integer 2 or greater and strictly less than the length
        of string
    post: returns a single string that is encoded with
        rail fence algorithm
    """
    rails = ['' for _ in range(key)]
    direction = 1
    row = 0
    for char in string:
        rails[row] += char
        if row == 0:
            direction = 1
        elif row == key - 1:
            direction = -1
        row += direction
    return ''.join(rails)


def rail_fence_decode(string, key):
    """
    pre: string is a string of characters and key is a positive
        integer 2 or greater and strictly less than the length
        of string
    post: function returns a single string that is decoded with
        rail fence algorithm
    """
    if key == 1:
        return string

    pattern = [['' for _ in range(len(string))] for _ in range(key)]
    row = 0
    direction = 1
    for col in range(len(string)):
        pattern[row][col] = '*'
        if row == 0:
            direction = 1
        elif row == key - 1:
            direction = -1
        row += direction

    str_idx = 0
    for r in range(key):
        for c in range(len(string)):
            if pattern[r][c] == '*' and str_idx < len(string):
                pattern[r][c] = string[str_idx]
                str_idx += 1

    result = ''
    row = 0
    direction = 1
    for col in range(len(string)):
        result += pattern[row][col]
        if row == 0:
            direction = 1
        elif row == key - 1:
            direction = -1
        row += direction
    return result


def filter_string(string):
    """
    pre: string is a string of characters
    post: function converts all characters to lower case and then
        removes all digits, punctuation marks, and spaces. It
        returns a single string with only lower case characters
    """

    result = ''
    for char in string.lower():
        if 'a' <= char <= 'z':
            result += char
    return result


def encode_character(p, s):
    """
    pre: p is a character in the pass phrase and s is a character
        in the plain text
    post: function returns a single character encoded using the
        Vigenere algorithm. You may not use a 2-D list
    """

    p_val = ord(p) - ord('a')
    s_val = ord(s) - ord('a')
    return chr((p_val + s_val) % 26 + ord('a'))


def decode_character(p, s):
    """
    pre: p is a character in the pass phrase and s is a character
        in the encrypted text
    post: function returns a single character decoded using the
        Vigenere algorithm. You may not use a 2-D list
    """

    p_val = ord(p) - ord('a')
    s_val = ord(s) - ord('a')
    return chr((s_val - p_val) % 26 + ord('a'))


def vigenere_encode(string, phrase):
    """
    pre: string is a string of characters and phrase is a pass phrase
    post: function returns a single string that is encoded with
        Vigenere algorithm
    """

    filtered_string = filter_string(string)
    filtered_phrase = filter_string(phrase)
    encoded = ''
    for i, char in enumerate(filtered_string):
        p_char = filtered_phrase[i % len(filtered_phrase)]
        encoded += encode_character(p_char, char)
    return encoded


def vigenere_decode(string, phrase):
    """
    pre: string is a string of characters and phrase is a pass phrase
    post: function returns a single string that is decoded with
        Vigenere algorithm
    """

    ciphertext = filter_string(ciphertext)
    passphrase = filter_string(passphrase)
    decoded = ''
    for i in range(len(ciphertext)):
        decoded += decode_character(passphrase[i % len(passphrase)], ciphertext[i])
    return decoded


def main():
    """Main function that reads stdin and runs each cipher"""

    plain_text = input().strip()
    key_encode = int(input().strip())
    encoded_text = input().strip()
    key_decode = int(input().strip())

    print("Rail Fence Cipher\n")
    print(f"Plain Text: {plain_text}")
    print(f"Key: {key_encode}")
    print(f"Encoded Text: {rail_fence_encode(plain_text, key_encode)}\n")

    print(f"Encoded Text: {encoded_text}")
    print(f"Enter Key: {key_decode}")
    print(f"Decoded Text: {rail_fence_decode(encoded_text, key_decode)}\n")

    plain_text_vigenere = input().strip()
    passphrase_encode = input().strip()
    encoded_text_vigenere = input().strip()
    passphrase_decode = input().strip()

    print("Vigenere Cipher\n")
    print(f"Plain Text: {plain_text_vigenere}")
    print(f"Pass Phrase: {passphrase_encode}")
    print(f"Encoded Text: {vigenere_encode(plain_text_vigenere, passphrase_encode)}\n")

    print(f"Encoded Text: {encoded_text_vigenere}")
    print(f"Pass Phrase: {passphrase_decode}")
    print(f"Decoded Text: {vigenere_decode(encoded_text_vigenere, passphrase_decode)}")

# Do NOT modify the following code.
if __name__ == "__main__":
    main()
